apiVersion: v1
kind: Secret
metadata:
  name: bot-hub-secrets
  namespace: hanzo
type: Opaque
stringData:
  DATABASE_URL: "postgresql://hub:CHANGE_ME@postgres.hanzo.svc:5432/hub"
  IAM_CLIENT_ID: "app-bothub"
  IAM_CLIENT_SECRET: "CHANGE_ME"
  S3_ACCESS_KEY: "hanzo"
  S3_SECRET_KEY: "CHANGE_ME"
  OPENAI_API_KEY: "CHANGE_ME"
