apiVersion: v1
kind: Service
metadata:
  name: bot-hub
  namespace: hanzo
spec:
  selector:
    app: bot-hub
  ports:
    - name: web
      port: 80
      targetPort: 3000
    - name: api
      port: 3001
      targetPort: 3001
